version: '3'

services:
  python-roadlinks-app:
    build:
      context: .
      dockerfile: processing-loading.dockerfile
    image: python-roadlinks-app
    container_name: python-roadlinks-app
    restart: always
    depends_on:
      - postgres
  jupyter:
    build:
      context: .
      dockerfile: jupyter.dockerfile
    image: compose-test
    container_name: jupyter-server
    restart: always
    port:
      - 5432:5432
    depends_on:
      - postgres
  postgres:
    image: postgres
    container_name: ${CONTAINER_NAME}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
    driver: local
